app = "redcrescent2"

[build]
  dockerfile = "Dockerfile"  # Use the Dockerfile you created


[[services]]
  internal_port = 8000
  protocol = "tcp"
  script = "gunicorn --bind 0.0.0.0:8000 redcrescent2.wsgi:application"